INSERT INTO post (title)
VALUES ('Post 1'),
       ('Post 2'),
       ('Post 3'),
       ('Post 4'),
       ('Post 5'),
       ('Post 6'),
       ('Post 7'),
       ('Post 8'),
       ('Post 9'),
       ('Post 10'),
       ('Post 11'),
       ('Post 12');

INSERT INTO comment (content, post_id)
VALUES ('Comment 1', 1),
       ('Comment 2', 1),
       ('Comment 3', 1),
       ('Comment 4', 2),
       ('Comment 5', 2),
       ('Comment 6', 2),
       ('Comment 7', 3),
       ('Comment 8', 3),
       ('Comment 9', 3),
       ('Comment 10', 4),
       ('Comment 11', 4),
       ('Comment 12', 4),
       ('Comment 13', 5),
       ('Comment 14', 5),
       ('Comment 15', 5),
       ('Comment 16', 6),
       ('Comment 17', 6),
       ('Comment 18', 6),
       ('Comment 19', 7),
       ('Comment 20', 7),
       ('Comment 21', 7),
       ('Comment 22', 8),
       ('Comment 23', 8),
       ('Comment 24', 8),
       ('Comment 25', 9),
       ('Comment 26', 9),
       ('Comment 27', 9),
       ('Comment 28', 10),
       ('Comment 29', 10),
       ('Comment 30', 10),
       ('Comment 31', 11),
       ('Comment 32', 11),
       ('Comment 33', 11),
       ('Comment 34', 12),
       ('Comment 35', 12),
       ('Comment 36', 12);
