management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true
