spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:test;
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

api-host: http://localhost:8080
client-host: http://localhost:8080

auth:
  github:
    client-id: 여기에 클라이언트 아이디를 입력하세요!
    client-secret: 여기에 클라이언트 시크릿을 입력하세요!
    redirect-uri: ${api-host}/auth/social/callback/github
    client-uri: ${client-host}

security:
  jwt:
    secret-key: 7b3dc341c033816045cc11c6f9fba3187f4dbdb7
    expiration-time: 86400000 # 1 day

