spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database;
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    defer-datasource-initialization: true


#logging:
#  level:
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.orm.transaction: DEBUG
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

