spring:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 500 # 이 부분이 batch fetch size 설정입니다.
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database;
    driver-class-name: org.h2.Driver

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
    org.hibernate.orm.jdbc.bind: trace
